### PR TITLE
fit: added git-workflows-superlinter template

### PR DESCRIPTION
**Pull request by thepatrickniyo**
#### What does this PR do?
- PR adds ``github-workflows-superlinter.yml`` template in CI templates

#### Description of Task to be completed?
- When ``superlinter`` option is checked, ``superlinter.yml``  template should be added under ``.github/workflows``

#### How should this be manually tested?
-  Clone the repo
-  Run ``npm install``
-  Checkout to branche ``ft-supelinter-template``
-  Run ``npm run test`` to run tests
-  Run ``npm run lint`` to lint the work

#### Any background context you want to provide?
- N/A

#### Screenshots (if appropriate
- N/A

### CODE REVIEW

**Comment by knowbee** [comment]
`superlinter template` won't be copied into `.github/workflows` under a given project but instead will be copied into project root directory.
Can you fix that ?

**Comment by thepatrickniyo** [comment]
> `superlinter template` won't be copied into `.github/workflows` under a given project but instead will be copied into project root directory.
> Can you fix that ?

cool, let me check on that

**Comment by thepatrickniyo** [comment]
@knowbee, You can re-review and let me know

**Comment by knowbee** [comment]
It is failing, trying to generate superlinter throws an error.

Os: macOs

**Comment by thepatrickniyo** [comment]
I'm using windows, can you share me the thrown error logs. That will help

**Comment by knowbee** [comment]
Error: ENOTSUP: operation not supported on socket, copyfile '/Users/knowbee/keza/lib/templates/.github' -> '.github'

**Pull request closed without merging**
